using System.Collections.Generic;

namespace ArchipelagoIntegration
{
    /// <summary>
    /// Maps Timberborn blueprint TemplateName values to Archipelago location names.
    /// Generated from the Folktails blueprint JSONs (ScienceCost > 0 only).
    /// </summary>
    internal static class ApBuildingLocations
    {
        private static readonly Dictionary<string, string> TemplateToLocation = new()
        {
            { "Agora.Folktails", "Science: Agora" },
            { "AquaticFarmhouse.Folktails", "Science: Aquatic Farmhouse" },
            { "AquiferDrill.Folktails", "Science: Aquifer Drill" },
            { "BadwaterDome.Folktails", "Science: Badwater Dome" },
            { "BadwaterPump.Folktails", "Science: Badwater Pump" },
            { "BadwaterRig.Folktails", "Science: Badwater Rig" },
            { "Bakery.Folktails", "Science: Bakery" },
            { "BeaverStatue.Folktails", "Science: Beaver Statue" },
            { "Beehive.Folktails", "Science: Beehive" },
            { "Bench.Folktails", "Science: Bench" },
            { "BotAssembler.Folktails", "Science: Bot Assembler" },
            { "BotPartFactory.Folktails", "Science: Bot Part Factory" },
            { "BrazierOfBonding.Folktails", "Science: Brazier of Bonding" },
            { "BuildersHut.Folktails", "Science: Builders' Hut" },
            { "BulletinPole.Folktails", "Science: Bulletin Pole" },
            { "Carousel.Folktails", "Science: Carousel" },
            { "Centrifuge.Folktails", "Science: Centrifuge" },
            { "Chronometer.Folktails", "Science: Chronometer" },
            { "Clutch.Folktails", "Science: Clutch" },
            { "ContaminationBarrier.Folktails", "Science: Contamination Barrier" },
            { "ContaminationSensor.Folktails", "Science: Contamination Sensor" },
            { "ContemplationSpot.Folktails", "Science: Contemplation Spot" },
            { "DanceHall.Folktails", "Science: Dance Hall" },
            { "DepthSensor.Folktails", "Science: Depth Sensor" },
            { "Detailer.Folktails", "Science: Detailer" },
            { "Detonator.Folktails", "Science: Detonator" },
            { "DirtExcavator.Folktails", "Science: Dirt Excavator" },
            { "DistrictCrossing.Folktails", "Science: District Crossing" },
            { "DoubleDynamite.Folktails", "Science: Double Dynamite" },
            { "DoubleFloodgate.Folktails", "Science: Double Floodgate" },
            { "DoubleLodge.Folktails", "Science: Double Lodge" },
            { "DoublePlatform.Folktails", "Science: Double Platform" },
            { "Dynamite.Folktails", "Science: Dynamite" },
            { "EarthRecultivator.Folktails", "Science: Earth Recultivator" },
            { "ExplosivesFactory.Folktails", "Science: Explosives Factory" },
            { "FarmerMonument.Folktails", "Science: Farmer Monument" },
            { "FireworkLauncher.Folktails", "Science: Firework Launcher" },
            { "Floodgate.Folktails", "Science: Floodgate" },
            { "FlowSensor.Folktails", "Science: Flow Sensor" },
            { "FluidDump.Folktails", "Science: Fluid Dump" },
            { "Forester.Folktails", "Science: Forester" },
            { "FountainOfJoy.Folktails", "Science: Fountain of Joy" },
            { "Gate.Folktails", "Science: Gate" },
            { "GearWorkshop.Folktails", "Science: Gear Workshop" },
            { "GeothermalEngine.Folktails", "Science: Geothermal Engine" },
            { "GravityBattery.Folktails", "Science: Gravity Battery" },
            { "Gristmill.Folktails", "Science: Gristmill" },
            { "Hammock.Folktails", "Science: Hammock" },
            { "Hedge.Folktails", "Science: Hedge" },
            { "Herbalist.Folktails", "Science: Herbalist" },
            { "HttpAdapter.Folktails", "Science: HTTP Adapter" },
            { "HttpLever.Folktails", "Science: HTTP Lever" },
            { "ImpermeableFloor.Folktails", "Science: Impermeable Floor" },
            { "Indicator.Folktails", "Science: Indicator" },
            { "Lantern.Folktails", "Science: Lantern" },
            { "LargeTank.Folktails", "Science: Large Tank" },
            { "LargeWarehouse.Folktails", "Science: Large Warehouse" },
            { "LargeWaterPump.Folktails", "Science: Large Water Pump" },
            { "LargeWindTurbine.Folktails", "Science: Large Wind Turbine" },
            { "Levee.Folktails", "Science: Levee" },
            { "Lever.Folktails", "Science: Lever" },
            { "Lido.Folktails", "Science: Lido" },
            { "MechanicalFluidPump.Folktails", "Science: Mechanical Fluid Pump" },
            { "MedicalBed.Folktails", "Science: Medical Bed" },
            { "MediumTank.Folktails", "Science: Medium Tank" },
            { "Memory.Folktails", "Science: Memory" },
            { "MetalPlatform3x3.Folktails", "Science: Metal Platform 3x3" },
            { "MetalPlatform5x5.Folktails", "Science: Metal Platform 5x5" },
            { "Mine.Folktails", "Science: Mine" },
            { "MiniLodge.Folktails", "Science: Mini Lodge" },
            { "MudPit.Folktails", "Science: Mud Pit" },
            { "Observatory.Folktails", "Science: Observatory" },
            { "Overhang2x1.Folktails", "Science: Overhang 2x1" },
            { "Overhang3x1.Folktails", "Science: Overhang 3x1" },
            { "Overhang4x1.Folktails", "Science: Overhang 4x1" },
            { "Overhang5x1.Folktails", "Science: Overhang 5x1" },
            { "Overhang6x1.Folktails", "Science: Overhang 6x1" },
            { "PaperMill.Folktails", "Science: Paper Mill" },
            { "Platform.Folktails", "Science: Platform" },
            { "PoleBanner.Folktails", "Science: Pole Banner" },
            { "PopulationCounter.Folktails", "Science: Population Counter" },
            { "PowerMeter.Folktails", "Science: Power Meter" },
            { "PrintingPress.Folktails", "Science: Printing Press" },
            { "Refinery.Folktails", "Science: Refinery" },
            { "Relay.Folktails", "Science: Relay" },
            { "ResourceCounter.Folktails", "Science: Resource Counter" },
            { "Roof1x1.Folktails", "Science: Roof 1x1" },
            { "Roof1x2.Folktails", "Science: Roof 1x2" },
            { "Roof2x2.Folktails", "Science: Roof 2x2" },
            { "Roof2x3.Folktails", "Science: Roof 2x3" },
            { "Roof3x2.Folktails", "Science: Roof 3x2" },
            { "Scarecrow.Folktails", "Science: Scarecrow" },
            { "ScavengerFlag.Folktails", "Science: Scavenger Flag" },
            { "ScienceCounter.Folktails", "Science: Science Counter" },
            { "Shower.Folktails", "Science: Shower" },
            { "Sluice.Folktails", "Science: Sluice" },
            { "Smelter.Folktails", "Science: Smelter" },
            { "Speaker.Folktails", "Science: Speaker" },
            { "SpiralStairs.Folktails", "Science: Spiral Stairs" },
            { "SquareBanner.Folktails", "Science: Square Banner" },
            { "Stairs.Folktails", "Science: Stairs" },
            { "StreamGauge.Folktails", "Science: Stream Gauge" },
            { "SuspensionBridge1x1.Folktails", "Science: Suspension Bridge 1x1" },
            { "SuspensionBridge2x1.Folktails", "Science: Suspension Bridge 2x1" },
            { "SuspensionBridge3x1.Folktails", "Science: Suspension Bridge 3x1" },
            { "SuspensionBridge4x1.Folktails", "Science: Suspension Bridge 4x1" },
            { "SuspensionBridge5x1.Folktails", "Science: Suspension Bridge 5x1" },
            { "SuspensionBridge6x1.Folktails", "Science: Suspension Bridge 6x1" },
            { "TappersShack.Folktails", "Science: Tapper's Shack" },
            { "TerrainBlock.Folktails", "Science: Terrain Block" },
            { "Timer.Folktails", "Science: Timer" },
            { "TripleDynamite.Folktails", "Science: Triple Dynamite" },
            { "TripleFloodgate.Folktails", "Science: Triple Floodgate" },
            { "TripleLodge.Folktails", "Science: Triple Lodge" },
            { "TriplePlatform.Folktails", "Science: Triple Platform" },
            { "Tunnel.Folktails", "Science: Tunnel" },
            { "UndergroundPile.Folktails", "Science: Underground Pile" },
            { "Valve.Folktails", "Science: Valve" },
            { "VerticalPowerShaft.Folktails", "Science: Vertical Power Shaft" },
            { "WeatherStation.Folktails", "Science: Weather Station" },
            { "Weathervane.Folktails", "Science: Weathervane" },
            { "WindTurbine.Folktails", "Science: Wind Turbine" },
            { "WoodFence.Folktails", "Science: Wood Fence" },
            { "WoodWorkshop.Folktails", "Science: Wood Workshop" },
            { "ZiplineBeam.Folktails", "Science: Zipline Beam" },
            { "ZiplinePylon.Folktails", "Science: Zipline Pylon" },
            { "ZiplineStation.Folktails", "Science: Zipline Station" },
        };

        public static bool TryGetLocationName(string templateName, out string locationName)
            => TemplateToLocation.TryGetValue(templateName, out locationName);

        public static IEnumerable<KeyValuePair<string, string>> AllEntries
            => TemplateToLocation;
    }
}
